### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by clemens-tolboom** [clemens-tolboom/godot_3_spawn_points#1]
### [Requirements](https://docs.godotengine.org/en/stable/tutorials/assetlib/uploading_to_assetlib.html?#requirements)

- [x] The asset must work. If the asset doesn't run or otherwise doesn't work in the specified Godot version, then it will be rejected.
- [x] The asset must have a proper .gitignore file. It's important to keep redundant data out of the repository. Here's a template. https://github.com/github/gitignore/blob/master/Godot.gitignore
- [x] No submodules, or any submodules must be non-essential. GitHub does not include submodules in the downloaded ZIP file, so if the asset needs the contents of the submodule, your asset won't work.
- [x] The license needs to be correct. The license listed on the asset library must match the license in the repository. The repo MUST have a license file, called either "LICENSE" or "LICENSE.md". This file must contain the license text itself and a copyright statement that includes the year(s) and copyright holder.
- [x] #6 Use proper English for the name
- [x]  #7 and description of your asset. This includes using correct capitalization, and using full sentences in the description.
- [x] #5 The icon link must be a direct link. For icons hosted on GitHub, the link must start with "raw.githubusercontent.com", not "github.com".

### [Recommendations](https://docs.godotengine.org/en/stable/tutorials/assetlib/uploading_to_assetlib.html?#recommendations)

- [ ] Fix or suppress all script warnings. The warning system is there to help identify issues with your code, but people using your asset don't need to see them.
- [ ] Make your code conform to the official style guides. Having a consistent style helps other people read your code, and it also helps if other people wish to contribute to your asset. See: the GDScript style guide or the C# style guide.
- [x] If you have screenshots in your repo, place them in their own subfolder and add a .gdignore file in the same folder (note: gd, not git). This prevents Godot from importing your screenshots. On Windows, open a command prompt in the project folder and run type nul > .gdignore to create a file whose name starts with a period.
- [x] If your asset is a library for working with other files, consider including example files in the asset.
- [x] #5 The icon should be a square, its aspect ratio should be 1:1. It should also ideally have a minimum resolution of 64x64 pixels.
- [x] While the asset library allows more than just GitHub, consider hosting your asset's source code on GitHub. Other services may not work reliably, and a lack of familiarity can be a barrier to contributors.

**Comment by clemens-tolboom** [comment]
Look OK to me ... so we can now create new version
